<?php
/**
 * Defines constants
 */
/**
 * Path to vendor/gb_common
 */
define('DRUPAL_MODS_ENV_DIR', DRUPAL_MODS_VENDOR. 'p1ratrulezzz/drupal_mods');

/**
 * Submodules directory
 */
define('DRUPAL_MODS_SUBMODULES_DIR', DRUPAL_MODS_ENV_DIR. '/submodules');

/*
 * Deprecated fallback compatible constants
 */
/*
 * @deprecated
 */
define('DRUPAL_MODS_MODULE_DIR', DRUPAL_MODS_ROOT);
define('DRUPAL_MODS', DRUPAL_MODS_ROOT);